### ISSUE TITLE
Database metadata graph enhancements

### ISSUE THREAD

**Issue by egpbos** [TICCLAT/ticclat_frontend#4]
On the metadata page, when zooming with the mouse wheel, the graph zooms in both dimensions. This feels a bit weird to me, but that might just be me. I'm not sure whether zooming really helps in any case for a histogram, so I would turn it off. If someone wants to know the values of the bars, this could maybe be implemented by displaying the value on hover.

Even if we want to keep the zooming in, it would be nice if this were disabled by default (I see there's a control button for it, so should be possible), because the more common action is to scroll the entire page in the browser, and this is now blocked when hovering over the graphs.

**Comment by Maartenvm** [comment]
moved issue
