### ISSUE TITLE
Crash when word not in database

### ISSUE THREAD

**Issue by egpbos** [TICCLAT/ticclat_frontend#5]
Try entering a word that's not in the database and the entire screen goes white. For instance "ramses" or "fierljeppe" (Frisian). Tested in Firefox, Chrome and Safari on macOS.

**Comment by egpbos** [comment]
@jvdzwaan is working on the backend side of this problem, which is caused by the variant endpoint not returning useful data, e.g. http://145.100.59.165:8000/variants/ramses or http://145.100.59.165:8000/variants/fierljeppe. Once the endpoint returns a sensible message, the frontend can use that to display something sensible as well.

**Comment by jvdzwaan** [comment]
Fixed by fixing the backend!
